# Form implementation generated from reading ui file 'calc_tax.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_calc_tax(object):
    def setupUi(self, calc_tax):
        calc_tax.setObjectName("calc_tax")
        calc_tax.resize(509, 398)
        calc_tax.setStyleSheet("QDialog {\n"
"    \n"
"    background-color: rgb(35, 40, 49);\n"
"    \n"
"    \n"
"}\n"
"QPushButton {\n"
"    background-color: rgb(22, 25, 31);\n"
"    color: white;\n"
"    font-size: 10pt;\n"
"    font-weight: 700;\n"
"    font-family: RussoOne-Regular;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #888;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: white;\n"
"    font-family: RussoOne-Regular;\n"
"    font-size: 10pt;\n"
"    font-weight: 600;\n"
"    background: rgb(76, 81, 93);\n"
"    min-width: 26ex;\n"
"    min-height: 4ex;\n"
"    \n"
"}\n"
"\n"
"QComboBox {\n"
"    color: white;\n"
"    font-family: RussoOne-Regular;\n"
"    font-size: 10pt;\n"
"    font-weight: 600;\n"
"    background: rgb(76, 81, 93);\n"
"    min-width: 26ex;\n"
"    min-height: 4ex;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background: rgb(76, 81, 93);\n"
"}\n"
"\n"
"QComboBox:on { \n"
"    background: rgb(76, 81, 93);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"  color: white;\n"
"  background-color: rgb(76, 81, 93);\n"
"  \n"
"  selection-background-color: rgb(39, 44, 54);\n"
"}\n"
"\n"
"QLineEdit {\n"
"    color: white;\n"
"    font-family: RussoOne-Regular;\n"
"    font-size: 12pt;\n"
"    font-weight: 600;\n"
"    background: rgb(76, 81, 93);\n"
"    border:1px;\n"
"   \n"
"    \n"
"\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(calc_tax)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_tax_kod = QtWidgets.QLabel(parent=calc_tax)
        font = QtGui.QFont()
        font.setFamily("RussoOne-Regular")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_tax_kod.setFont(font)
        self.lbl_tax_kod.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_tax_kod.setObjectName("lbl_tax_kod")
        self.gridLayout.addWidget(self.lbl_tax_kod, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.btn_ok = QtWidgets.QPushButton(parent=calc_tax)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ok.sizePolicy().hasHeightForWidth())
        self.btn_ok.setSizePolicy(sizePolicy)
        self.btn_ok.setObjectName("btn_ok")
        self.gridLayout.addWidget(self.btn_ok, 7, 0, 1, 2)
        self.cmb_count_origin = QtWidgets.QComboBox(parent=calc_tax)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmb_count_origin.sizePolicy().hasHeightForWidth())
        self.cmb_count_origin.setSizePolicy(sizePolicy)
        self.cmb_count_origin.setEditable(False)
        self.cmb_count_origin.setObjectName("cmb_count_origin")
        self.gridLayout.addWidget(self.cmb_count_origin, 4, 1, 1, 1)
        self.lbl_count_orig = QtWidgets.QLabel(parent=calc_tax)
        font = QtGui.QFont()
        font.setFamily("RussoOne-Regular")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_count_orig.setFont(font)
        self.lbl_count_orig.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_count_orig.setObjectName("lbl_count_orig")
        self.gridLayout.addWidget(self.lbl_count_orig, 4, 0, 1, 1)
        self.lbl_nbr_inv = QtWidgets.QLabel(parent=calc_tax)
        font = QtGui.QFont()
        font.setFamily("RussoOne-Regular")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_nbr_inv.setFont(font)
        self.lbl_nbr_inv.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_nbr_inv.setObjectName("lbl_nbr_inv")
        self.gridLayout.addWidget(self.lbl_nbr_inv, 2, 0, 1, 1)
        self.lbl_value = QtWidgets.QLabel(parent=calc_tax)
        font = QtGui.QFont()
        font.setFamily("RussoOne-Regular")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_value.setFont(font)
        self.lbl_value.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_value.setObjectName("lbl_value")
        self.gridLayout.addWidget(self.lbl_value, 3, 0, 1, 1)
        self.lne_value = QtWidgets.QLineEdit(parent=calc_tax)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lne_value.sizePolicy().hasHeightForWidth())
        self.lne_value.setSizePolicy(sizePolicy)
        self.lne_value.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.lne_value.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lne_value.setObjectName("lne_value")
        self.gridLayout.addWidget(self.lne_value, 3, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        self.gridLayout.addItem(spacerItem1, 6, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        self.gridLayout.addItem(spacerItem2, 8, 0, 1, 1)
        self.lne_tax_kod = QtWidgets.QLineEdit(parent=calc_tax)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lne_tax_kod.sizePolicy().hasHeightForWidth())
        self.lne_tax_kod.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("RussoOne-Regular")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.NoAntialias)
        self.lne_tax_kod.setFont(font)
        self.lne_tax_kod.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.lne_tax_kod.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lne_tax_kod.setObjectName("lne_tax_kod")
        self.gridLayout.addWidget(self.lne_tax_kod, 1, 1, 1, 1)
        self.lne_mass = QtWidgets.QLineEdit(parent=calc_tax)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lne_mass.sizePolicy().hasHeightForWidth())
        self.lne_mass.setSizePolicy(sizePolicy)
        self.lne_mass.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.lne_mass.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lne_mass.setObjectName("lne_mass")
        self.gridLayout.addWidget(self.lne_mass, 2, 1, 1, 1)

        self.retranslateUi(calc_tax)
        QtCore.QMetaObject.connectSlotsByName(calc_tax)
        calc_tax.setTabOrder(self.lne_tax_kod, self.lne_mass)
        calc_tax.setTabOrder(self.lne_mass, self.lne_value)
        calc_tax.setTabOrder(self.lne_value, self.cmb_count_origin)
        calc_tax.setTabOrder(self.cmb_count_origin, self.btn_ok)

    def retranslateUi(self, calc_tax):
        _translate = QtCore.QCoreApplication.translate
        calc_tax.setWindowTitle(_translate("calc_tax", "Dialog"))
        self.lbl_tax_kod.setText(_translate("calc_tax", "Код товара"))
        self.btn_ok.setText(_translate("calc_tax", "OK"))
        self.lbl_count_orig.setText(_translate("calc_tax", "Страна происхождения"))
        self.lbl_nbr_inv.setText(_translate("calc_tax", "Вес нетто"))
        self.lbl_value.setText(_translate("calc_tax", "Стоимость (EUR)"))
