# Form implementation generated from reading ui file 'consignor_dest.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_consignor_destination(object):
    def setupUi(self, consignor_destination):
        consignor_destination.setObjectName("consignor_destination")
        consignor_destination.resize(645, 327)
        consignor_destination.setStyleSheet("QDialog {\n"
"    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid gray;\n"
"    border-radius: 10px;\n"
"    \n"
"    \n"
"}\n"
"QPushButton {\n"
"    background-color: rgb(22, 25, 31);\n"
"    color: white;\n"
"    font-size: 10pt;\n"
"    font-weight: 700;\n"
"    font-family: RussoOne-Regular;\n"
"    border: 1px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #888;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: white;\n"
"    font-family: RussoOne-Regular;\n"
"    font-size: 10pt;\n"
"    font-weight: 600;\n"
"    background: rgb(76, 81, 93);\n"
"    min-width: 26ex;\n"
"    min-height: 4ex;\n"
"    border: 1px;\n"
"    border-radius: 10px;\n"
"    \n"
"}\n"
"\n"
"QComboBox {\n"
"    color: white;\n"
"    font-family: RussoOne-Regular;\n"
"    font-size: 12pt;\n"
"    font-weight: 600;\n"
"    background: rgb(76, 81, 93);\n"
"    min-width: 26ex;\n"
"    min-height: 4ex;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"    border: 1px;\n"
"    border-radius: 10px;\n"
"\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background: rgb(76, 81, 93);\n"
"}\n"
"\n"
"QComboBox:on { \n"
"    background: rgb(76, 81, 93);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"  color: white;\n"
"  background-color: rgb(76, 81, 93);\n"
"  \n"
"  selection-background-color: rgb(39, 44, 54);\n"
"}\n"
"\n"
"QLineEdit {\n"
"    color: white;\n"
"    font-family: RussoOne-Regular;\n"
"    font-size: 14pt;\n"
"    font-weight: 600;\n"
"    background: rgb(76, 81, 93);\n"
"    border:1px;\n"
"    border-radius: 10px;\n"
"   \n"
"    \n"
"\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(consignor_destination)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(parent=consignor_destination)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.cmb_country = QtWidgets.QComboBox(parent=consignor_destination)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmb_country.sizePolicy().hasHeightForWidth())
        self.cmb_country.setSizePolicy(sizePolicy)
        self.cmb_country.setObjectName("cmb_country")
        self.gridLayout.addWidget(self.cmb_country, 5, 1, 1, 1)
        self.lne_name = QtWidgets.QLineEdit(parent=consignor_destination)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lne_name.sizePolicy().hasHeightForWidth())
        self.lne_name.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("RussoOne-Regular")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lne_name.setFont(font)
        self.lne_name.setStyleSheet("QLineEdit {\n"
"    color: white;\n"
"    font-family: RussoOne-Regular;\n"
"    font-size: 12pt;\n"
"    font-weight: 600;\n"
"    background: rgb(76, 81, 93);\n"
"    border:1px;\n"
"   \n"
"    \n"
"\n"
"}")
        self.lne_name.setMaxLength(35)
        self.lne_name.setObjectName("lne_name")
        self.gridLayout.addWidget(self.lne_name, 1, 1, 1, 4)
        self.lne_adres = QtWidgets.QLineEdit(parent=consignor_destination)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lne_adres.sizePolicy().hasHeightForWidth())
        self.lne_adres.setSizePolicy(sizePolicy)
        self.lne_adres.setStyleSheet("QLineEdit {\n"
"    color: white;\n"
"    font-family: RussoOne-Regular;\n"
"    font-size: 12pt;\n"
"    font-weight: 600;\n"
"    background: rgb(76, 81, 93);\n"
"    border:1px;\n"
"   \n"
"    \n"
"\n"
"}")
        self.lne_adres.setMaxLength(35)
        self.lne_adres.setObjectName("lne_adres")
        self.gridLayout.addWidget(self.lne_adres, 7, 1, 1, 4)
        self.btn_ok = QtWidgets.QPushButton(parent=consignor_destination)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ok.sizePolicy().hasHeightForWidth())
        self.btn_ok.setSizePolicy(sizePolicy)
        self.btn_ok.setObjectName("btn_ok")
        self.gridLayout.addWidget(self.btn_ok, 8, 0, 1, 5)
        self.lbl_name = QtWidgets.QLabel(parent=consignor_destination)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_name.sizePolicy().hasHeightForWidth())
        self.lbl_name.setSizePolicy(sizePolicy)
        self.lbl_name.setObjectName("lbl_name")
        self.gridLayout.addWidget(self.lbl_name, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=consignor_destination)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setTabletTracking(True)
        self.label_2.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 5)
        self.lbl_adres = QtWidgets.QLabel(parent=consignor_destination)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_adres.sizePolicy().hasHeightForWidth())
        self.lbl_adres.setSizePolicy(sizePolicy)
        self.lbl_adres.setObjectName("lbl_adres")
        self.gridLayout.addWidget(self.lbl_adres, 7, 0, 1, 1)
        self.lne_zipkod = QtWidgets.QLineEdit(parent=consignor_destination)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lne_zipkod.sizePolicy().hasHeightForWidth())
        self.lne_zipkod.setSizePolicy(sizePolicy)
        self.lne_zipkod.setStyleSheet("QLineEdit {\n"
"    color: white;\n"
"    font-family: RussoOne-Regular;\n"
"    font-size: 12pt;\n"
"    font-weight: 600;\n"
"    background: rgb(76, 81, 93);\n"
"    border:1px;\n"
"   \n"
"    \n"
"\n"
"}")
        self.lne_zipkod.setMaxLength(10)
        self.lne_zipkod.setObjectName("lne_zipkod")
        self.gridLayout.addWidget(self.lne_zipkod, 4, 1, 1, 1)
        self.lne_city = QtWidgets.QLineEdit(parent=consignor_destination)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lne_city.sizePolicy().hasHeightForWidth())
        self.lne_city.setSizePolicy(sizePolicy)
        self.lne_city.setStyleSheet("QLineEdit {\n"
"    color: white;\n"
"    font-family: RussoOne-Regular;\n"
"    font-size: 12pt;\n"
"    font-weight: 600;\n"
"    background: rgb(76, 81, 93);\n"
"    border:1px;\n"
"   \n"
"    \n"
"\n"
"}")
        self.lne_city.setMaxLength(35)
        self.lne_city.setObjectName("lne_city")
        self.gridLayout.addWidget(self.lne_city, 6, 1, 1, 4)
        self.lbl_city = QtWidgets.QLabel(parent=consignor_destination)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_city.sizePolicy().hasHeightForWidth())
        self.lbl_city.setSizePolicy(sizePolicy)
        self.lbl_city.setObjectName("lbl_city")
        self.gridLayout.addWidget(self.lbl_city, 6, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=consignor_destination)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)

        self.retranslateUi(consignor_destination)
        QtCore.QMetaObject.connectSlotsByName(consignor_destination)
        consignor_destination.setTabOrder(self.lne_name, self.lne_zipkod)
        consignor_destination.setTabOrder(self.lne_zipkod, self.cmb_country)
        consignor_destination.setTabOrder(self.cmb_country, self.lne_city)
        consignor_destination.setTabOrder(self.lne_city, self.lne_adres)
        consignor_destination.setTabOrder(self.lne_adres, self.btn_ok)

    def retranslateUi(self, consignor_destination):
        _translate = QtCore.QCoreApplication.translate
        consignor_destination.setWindowTitle(_translate("consignor_destination", "Получатель CMR № "))
        self.label_3.setText(_translate("consignor_destination", "    Страна"))
        self.btn_ok.setText(_translate("consignor_destination", "OK"))
        self.lbl_name.setText(_translate("consignor_destination", "    Наименование"))
        self.label_2.setText(_translate("consignor_destination", "Получатель"))
        self.lbl_adres.setText(_translate("consignor_destination", "    Адрес"))
        self.lbl_city.setText(_translate("consignor_destination", "    Город"))
        self.label_4.setText(_translate("consignor_destination", "    Почтовый код    "))
