# Form implementation generated from reading ui file 'convert.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(750, 624)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setStyleSheet("QMainWindow {\n"
"    \n"
"    background-color: rgb(22, 25, 31);\n"
"    border: 2px solid gray;\n"
"    border-radius: 10px;\n"
"    \n"
"    \n"
"}\n"
"QPushButton {\n"
"    background-color: rgb(22, 25, 31);\n"
"    color: white;\n"
"    font-size: 10pt;\n"
"    font-weight: 700;\n"
"    font-family: RussoOne-Regular;\n"
"    border:1px;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #888;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    font-family: RussoOne-Regular;\n"
"    font-size: 6pt;\n"
"    font-weight: 600;\n"
"    \n"
"    min-width: 26ex;\n"
"    min-height: 4ex;\n"
"    \n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 1, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(200, 30))
        self.tabWidget.setToolTip("")
        self.tabWidget.setWhatsThis("")
        self.tabWidget.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.tabWidget.setStyleSheet("QTabWidget:pane {\n"
"    border:1px;\n"
"\n"
"    border-radius: 20px;\n"
"    background-color: rgb(35, 40, 49);\n"
"}\n"
"\n"
"QTabBar:tab {\n"
"    color: white;\n"
"    font-family: Rubik;\n"
"    font-size: 8pt;\n"
"    font-weight: 600;\n"
"    background: rgb(76, 81, 93);\n"
"    min-width: 26ex;\n"
"    min-height: 4ex;\n"
"    margin-left: 2px;\n"
"    left: -2px;\n"
"    border:1px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QTabBar:tab:selected {\n"
"    background: rgb(35,40,49)\n"
"}\n"
"\n"
"\n"
"QTabBar:tab:hover {\n"
"    background: rgb(56,62,73)\n"
"}\n"
"\n"
"")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(20, 20))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab.sizePolicy().hasHeightForWidth())
        self.tab.setSizePolicy(sizePolicy)
        self.tab.setStyleSheet("")
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_translate = QtWidgets.QPushButton(parent=self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_translate.sizePolicy().hasHeightForWidth())
        self.btn_translate.setSizePolicy(sizePolicy)
        self.btn_translate.setStyleSheet("")
        self.btn_translate.setObjectName("btn_translate")
        self.gridLayout_2.addWidget(self.btn_translate, 2, 0, 1, 1)
        self.btn_select_file = QtWidgets.QPushButton(parent=self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_select_file.sizePolicy().hasHeightForWidth())
        self.btn_select_file.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("RussoOne-Regular")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(87)
        self.btn_select_file.setFont(font)
        self.btn_select_file.setStyleSheet("")
        self.btn_select_file.setObjectName("btn_select_file")
        self.gridLayout_2.addWidget(self.btn_select_file, 0, 0, 1, 1)
        self.lbl_group_kod = QtWidgets.QLabel(parent=self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_group_kod.sizePolicy().hasHeightForWidth())
        self.lbl_group_kod.setSizePolicy(sizePolicy)
        self.lbl_group_kod.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    font-family: RussoOne-Regular;\n"
"    font-size: 10pt;\n"
"    font-weight: 600;\n"
"    \n"
"    min-width: 26ex;\n"
"    min-height: 4ex;\n"
"    \n"
"}")
        self.lbl_group_kod.setText("")
        self.lbl_group_kod.setObjectName("lbl_group_kod")
        self.gridLayout_2.addWidget(self.lbl_group_kod, 1, 1, 1, 1)
        self.lbl_input_file = QtWidgets.QLabel(parent=self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_input_file.sizePolicy().hasHeightForWidth())
        self.lbl_input_file.setSizePolicy(sizePolicy)
        self.lbl_input_file.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    font-family: RussoOne-Regular;\n"
"    font-size: 10pt;\n"
"    font-weight: 600;\n"
"    \n"
"    min-width: 26ex;\n"
"    min-height: 4ex;\n"
"    \n"
"}")
        self.lbl_input_file.setText("")
        self.lbl_input_file.setObjectName("lbl_input_file")
        self.gridLayout_2.addWidget(self.lbl_input_file, 0, 1, 1, 1)
        self.btn_group_kod = QtWidgets.QPushButton(parent=self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_group_kod.sizePolicy().hasHeightForWidth())
        self.btn_group_kod.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("RussoOne-Regular")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(87)
        self.btn_group_kod.setFont(font)
        self.btn_group_kod.setStyleSheet("color: white;\n"
"QPushButton: {\n"
"    background-color: transparent;\n"
"}\n"
"")
        self.btn_group_kod.setObjectName("btn_group_kod")
        self.gridLayout_2.addWidget(self.btn_group_kod, 1, 0, 1, 1)
        self.btn_load_csv = QtWidgets.QPushButton(parent=self.tab)
        self.btn_load_csv.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_load_csv.sizePolicy().hasHeightForWidth())
        self.btn_load_csv.setSizePolicy(sizePolicy)
        self.btn_load_csv.setStyleSheet("")
        self.btn_load_csv.setObjectName("btn_load_csv")
        self.gridLayout_2.addWidget(self.btn_load_csv, 3, 0, 1, 2)
        self.btn_load_tardek = QtWidgets.QPushButton(parent=self.tab)
        self.btn_load_tardek.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_load_tardek.sizePolicy().hasHeightForWidth())
        self.btn_load_tardek.setSizePolicy(sizePolicy)
        self.btn_load_tardek.setStyleSheet("")
        self.btn_load_tardek.setObjectName("btn_load_tardek")
        self.gridLayout_2.addWidget(self.btn_load_tardek, 4, 0, 1, 2)
        self.lbl_translate = QtWidgets.QLabel(parent=self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_translate.sizePolicy().hasHeightForWidth())
        self.lbl_translate.setSizePolicy(sizePolicy)
        self.lbl_translate.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    font-family: RussoOne-Regular;\n"
"    font-size: 10pt;\n"
"    font-weight: 600;\n"
"    \n"
"    min-width: 26ex;\n"
"    min-height: 4ex;\n"
"    \n"
"}")
        self.lbl_translate.setText("")
        self.lbl_translate.setObjectName("lbl_translate")
        self.gridLayout_2.addWidget(self.lbl_translate, 2, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_3.addItem(spacerItem, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_2.sizePolicy().hasHeightForWidth())
        self.tab_2.setSizePolicy(sizePolicy)
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.btn_calc_tax = QtWidgets.QPushButton(parent=self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_calc_tax.sizePolicy().hasHeightForWidth())
        self.btn_calc_tax.setSizePolicy(sizePolicy)
        self.btn_calc_tax.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_calc_tax.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.btn_calc_tax.setStyleSheet("QPushButton {\n"
"    background-color: rgb(22, 25, 31);\n"
"    color: white;\n"
"    font-size: 10pt;\n"
"    font-weight: 700;\n"
"    font-family: RussoOne-Regular;\n"
"    border:1px;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #888;\n"
"}\n"
"")
        self.btn_calc_tax.setObjectName("btn_calc_tax")
        self.verticalLayout_10.addWidget(self.btn_calc_tax)
        spacerItem1 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_10.addItem(spacerItem1)
        self.btn_calc_csv = QtWidgets.QPushButton(parent=self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_calc_csv.sizePolicy().hasHeightForWidth())
        self.btn_calc_csv.setSizePolicy(sizePolicy)
        self.btn_calc_csv.setObjectName("btn_calc_csv")
        self.verticalLayout_10.addWidget(self.btn_calc_csv)
        spacerItem2 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_10.addItem(spacerItem2)
        self.btn_calc_lv = QtWidgets.QPushButton(parent=self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_calc_lv.sizePolicy().hasHeightForWidth())
        self.btn_calc_lv.setSizePolicy(sizePolicy)
        self.btn_calc_lv.setObjectName("btn_calc_lv")
        self.verticalLayout_10.addWidget(self.btn_calc_lv)
        spacerItem3 = QtWidgets.QSpacerItem(20, 150, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_10.addItem(spacerItem3)
        self.gridLayout_5.addLayout(self.verticalLayout_10, 2, 0, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_warning = QtWidgets.QLabel(parent=self.tab_2)
        self.label_warning.setStyleSheet("QLabel {\n"
"    color: red;\n"
"    font-family: RussoOne-Regular;\n"
"    font-size: 8pt;\n"
"    font-weight: 600;\n"
"    \n"
"    min-width: 26ex;\n"
"    min-height: 4ex;\n"
"    \n"
"}")
        self.label_warning.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_warning.setObjectName("label_warning")
        self.verticalLayout_9.addWidget(self.label_warning, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.gridLayout_5.addLayout(self.verticalLayout_9, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_5.addItem(spacerItem4, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_create_payment = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_create_payment.sizePolicy().hasHeightForWidth())
        self.tab_create_payment.setSizePolicy(sizePolicy)
        self.tab_create_payment.setStyleSheet("QCalendarWidget QWidget {\n"
"\n"
"    alternate-background-color: rgb(136, 136, 136); \n"
"    \n"
"\n"
"}\n"
"\n"
"#qt_calendar_navigationbar {\n"
"    \n"
"    min-height: 50px;\n"
"}\n"
"\n"
"QCalendarWidget QAbstractItemView:disabled \n"
"{ \n"
"    color: rgb(64, 64, 64); \n"
"}\n"
"\n"
"\n"
"QCalendarWidget QMenu {\n"
"      width: 150px;\n"
"      left: 20px;\n"
"      color: white;\n"
"      font-size: 14px;\n"
"    font-family: RussoOne-Regular;\n"
"      background-color: black;\n"
"    selection-background-color: white;\n"
"    selection-color: black;\n"
"    \n"
"  }\n"
"\n"
"\n"
"\n"
"QCalendarWidget QSpinBox { \n"
"      width: 100px; \n"
"    height: 100px;\n"
"      font-size:14px; \n"
"      color: white; \n"
"      background-color: rgb(64, 64, 64);\n"
"      selection-background-color: rgb(136, 136, 136);\n"
"      \n"
"  }\n"
"   \n"
"QCalendarWidget QToolButton {\n"
"    width: 120 px;\n"
"    height: 40 px;\n"
"    background-color: black;\n"
"    color: white;\n"
"    font-size: 14pt;\n"
"    font-weight: 600;\n"
"    font-family: RussoOne-Regular;\n"
"    icon-size: 56px, 56px;\n"
"}\n"
"\n"
"QCalendarWidget QToolButton:hover {\n"
"    background-color: #666;\n"
"}\n"
"\n"
"QCalendarWidget QToolButton:pressed {\n"
"    background-color: red;\n"
"}\n"
"\n"
"QCalendarWidget QAbstractItemView:enabled {\n"
"      font-size:14px;\n"
"    font-weight: 600;\n"
"      color: rgb(180, 180, 180);  \n"
"      background-color: rgb(35, 40, 49);  \n"
"      selection-background-color: rgb(64, 64, 64); \n"
"      selection-color: rgb(0, 255, 0); \n"
"}\n"
"\n"
"QCalendarWidget QWidget#qt_calendar_navigationbar{ \n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop: 0 #cccccc, stop: 1 #333333); \n"
"}\n"
"QLabel {\n"
"    color: white;\n"
"    font-family: RussoOne-Regular;\n"
"    font-size: 10pt;\n"
"    font-weight: 600;\n"
"    background-color: rgb(22, 25, 31);\n"
"    border:1px;\n"
"    border-radius: 10px;\n"
"    \n"
"    \n"
"}\n"
"\n"
"QLineEdit {\n"
"    color: white;\n"
"    font-family: RussoOne-Regular;\n"
"    font-size: 14pt;\n"
"    font-weight: 600;\n"
"    background: rgb(76, 81, 93);\n"
"    border:1px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QTextEdit {\n"
"    color: white;\n"
"    font-family: RussoOne-Regular;\n"
"    font-size: 14pt;\n"
"    font-weight: 600;\n"
"    background: rgb(76, 81, 93);\n"
"    border:1px;\n"
" \n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QRadioButton {\n"
"    spacing: 10 px;\n"
"    color: white;\n"
"    font-family: RussoOne-Regular;\n"
"    font-size: 10pt;\n"
"    font-weight: 600;\n"
"    background-color: rgb(22, 25, 31);\n"
"    border: 2px solid grey;\n"
"    border-radius: 10px;\n"
"   \n"
"}\n"
"\n"
"QDateEdit {\n"
"    color: white;\n"
"    font-family: RussoOne-Regular;\n"
"    font-size: 10pt;\n"
"    font-weight: 600;\n"
"    \n"
"    background: rgb(76, 81, 93);\n"
"   \n"
"    selection-background-color: rgb(39, 44, 54);\n"
"    background-color: rgb(76, 81, 93);\n"
"    border: 1px;\n"
"    border-radius: 10px;\n"
"    \n"
"\n"
"}\n"
"\n"
"QRadioButton:indicator {\n"
"    left: 10 px;\n"
"    width: 13px;\n"
"    height: 13px;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.tab_create_payment.setObjectName("tab_create_payment")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_create_payment)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lbl_avto = QtWidgets.QLabel(parent=self.tab_create_payment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_avto.sizePolicy().hasHeightForWidth())
        self.lbl_avto.setSizePolicy(sizePolicy)
        self.lbl_avto.setMinimumSize(QtCore.QSize(200, 30))
        self.lbl_avto.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lbl_avto.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_avto.setObjectName("lbl_avto")
        self.verticalLayout_8.addWidget(self.lbl_avto)
        self.lne_avto = QtWidgets.QLineEdit(parent=self.tab_create_payment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lne_avto.sizePolicy().hasHeightForWidth())
        self.lne_avto.setSizePolicy(sizePolicy)
        self.lne_avto.setMinimumSize(QtCore.QSize(200, 30))
        self.lne_avto.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lne_avto.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lne_avto.setObjectName("lne_avto")
        self.verticalLayout_8.addWidget(self.lne_avto)
        self.gridLayout.addLayout(self.verticalLayout_8, 1, 2, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem5)
        self.lbl_vid = QtWidgets.QLabel(parent=self.tab_create_payment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_vid.sizePolicy().hasHeightForWidth())
        self.lbl_vid.setSizePolicy(sizePolicy)
        self.lbl_vid.setMinimumSize(QtCore.QSize(200, 30))
        self.lbl_vid.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lbl_vid.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_vid.setObjectName("lbl_vid")
        self.verticalLayout_5.addWidget(self.lbl_vid)
        self.txt_vet_edit = QtWidgets.QTextEdit(parent=self.tab_create_payment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_vet_edit.sizePolicy().hasHeightForWidth())
        self.txt_vet_edit.setSizePolicy(sizePolicy)
        self.txt_vet_edit.setMinimumSize(QtCore.QSize(160, 150))
        self.txt_vet_edit.setMaximumSize(QtCore.QSize(160, 150))
        font = QtGui.QFont()
        font.setFamily("RussoOne-Regular")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.txt_vet_edit.setFont(font)
        self.txt_vet_edit.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.txt_vet_edit.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.txt_vet_edit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.txt_vet_edit.setAutoFormatting(QtWidgets.QTextEdit.AutoFormattingFlag.AutoBulletList)
        self.txt_vet_edit.setTabChangesFocus(False)
        self.txt_vet_edit.setObjectName("txt_vet_edit")
        self.verticalLayout_5.addWidget(self.txt_vet_edit)
        self.dte_vet = QtWidgets.QDateEdit(parent=self.tab_create_payment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dte_vet.sizePolicy().hasHeightForWidth())
        self.dte_vet.setSizePolicy(sizePolicy)
        self.dte_vet.setMinimumSize(QtCore.QSize(160, 30))
        self.dte_vet.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.dte_vet.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.dte_vet.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.dte_vet.setCurrentSection(QtWidgets.QDateTimeEdit.Section.YearSection)
        self.dte_vet.setCalendarPopup(True)
        self.dte_vet.setObjectName("dte_vet")
        self.verticalLayout_5.addWidget(self.dte_vet)
        self.gridLayout.addLayout(self.verticalLayout_5, 2, 2, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.btn_create_pay = QtWidgets.QPushButton(parent=self.tab_create_payment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_create_pay.sizePolicy().hasHeightForWidth())
        self.btn_create_pay.setSizePolicy(sizePolicy)
        self.btn_create_pay.setMinimumSize(QtCore.QSize(100, 50))
        self.btn_create_pay.setObjectName("btn_create_pay")
        self.verticalLayout_7.addWidget(self.btn_create_pay)
        self.gridLayout.addLayout(self.verticalLayout_7, 3, 0, 1, 3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lbl_pereh = QtWidgets.QLabel(parent=self.tab_create_payment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_pereh.sizePolicy().hasHeightForWidth())
        self.lbl_pereh.setSizePolicy(sizePolicy)
        self.lbl_pereh.setMinimumSize(QtCore.QSize(220, 30))
        self.lbl_pereh.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lbl_pereh.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_pereh.setObjectName("lbl_pereh")
        self.verticalLayout_3.addWidget(self.lbl_pereh)
        self.rdi_kyb = QtWidgets.QRadioButton(parent=self.tab_create_payment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rdi_kyb.sizePolicy().hasHeightForWidth())
        self.rdi_kyb.setSizePolicy(sizePolicy)
        self.rdi_kyb.setMinimumSize(QtCore.QSize(150, 30))
        self.rdi_kyb.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.rdi_kyb.setObjectName("rdi_kyb")
        self.verticalLayout_3.addWidget(self.rdi_kyb)
        self.rdi_sal = QtWidgets.QRadioButton(parent=self.tab_create_payment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rdi_sal.sizePolicy().hasHeightForWidth())
        self.rdi_sal.setSizePolicy(sizePolicy)
        self.rdi_sal.setMinimumSize(QtCore.QSize(150, 30))
        self.rdi_sal.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.rdi_sal.setObjectName("rdi_sal")
        self.verticalLayout_3.addWidget(self.rdi_sal)
        self.rdi_lav = QtWidgets.QRadioButton(parent=self.tab_create_payment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rdi_lav.sizePolicy().hasHeightForWidth())
        self.rdi_lav.setSizePolicy(sizePolicy)
        self.rdi_lav.setMinimumSize(QtCore.QSize(150, 30))
        self.rdi_lav.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.rdi_lav.setObjectName("rdi_lav")
        self.verticalLayout_3.addWidget(self.rdi_lav)
        self.rdi_med = QtWidgets.QRadioButton(parent=self.tab_create_payment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rdi_med.sizePolicy().hasHeightForWidth())
        self.rdi_med.setSizePolicy(sizePolicy)
        self.rdi_med.setMinimumSize(QtCore.QSize(150, 30))
        self.rdi_med.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.rdi_med.setObjectName("rdi_med")
        self.verticalLayout_3.addWidget(self.rdi_med)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 2, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem7)
        self.lbl_chedp = QtWidgets.QLabel(parent=self.tab_create_payment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_chedp.sizePolicy().hasHeightForWidth())
        self.lbl_chedp.setSizePolicy(sizePolicy)
        self.lbl_chedp.setMinimumSize(QtCore.QSize(200, 30))
        self.lbl_chedp.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lbl_chedp.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_chedp.setObjectName("lbl_chedp")
        self.verticalLayout_4.addWidget(self.lbl_chedp)
        self.txt_ched_edit = QtWidgets.QTextEdit(parent=self.tab_create_payment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_ched_edit.sizePolicy().hasHeightForWidth())
        self.txt_ched_edit.setSizePolicy(sizePolicy)
        self.txt_ched_edit.setMinimumSize(QtCore.QSize(250, 150))
        self.txt_ched_edit.setMaximumSize(QtCore.QSize(250, 150))
        font = QtGui.QFont()
        font.setFamily("RussoOne-Regular")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.txt_ched_edit.setFont(font)
        self.txt_ched_edit.setObjectName("txt_ched_edit")
        self.verticalLayout_4.addWidget(self.txt_ched_edit)
        self.dte_chedpp = QtWidgets.QDateEdit(parent=self.tab_create_payment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dte_chedpp.sizePolicy().hasHeightForWidth())
        self.dte_chedpp.setSizePolicy(sizePolicy)
        self.dte_chedpp.setMinimumSize(QtCore.QSize(160, 30))
        self.dte_chedpp.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.dte_chedpp.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.dte_chedpp.setCurrentSection(QtWidgets.QDateTimeEdit.Section.YearSection)
        self.dte_chedpp.setCalendarPopup(True)
        self.dte_chedpp.setObjectName("dte_chedpp")
        self.verticalLayout_4.addWidget(self.dte_chedpp)
        self.gridLayout.addLayout(self.verticalLayout_4, 2, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_poruch = QtWidgets.QLabel(parent=self.tab_create_payment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_poruch.sizePolicy().hasHeightForWidth())
        self.lbl_poruch.setSizePolicy(sizePolicy)
        self.lbl_poruch.setMinimumSize(QtCore.QSize(160, 30))
        self.lbl_poruch.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lbl_poruch.setStyleSheet("")
        self.lbl_poruch.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_poruch.setObjectName("lbl_poruch")
        self.verticalLayout_2.addWidget(self.lbl_poruch)
        self.lne_poruch = QtWidgets.QLineEdit(parent=self.tab_create_payment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lne_poruch.sizePolicy().hasHeightForWidth())
        self.lne_poruch.setSizePolicy(sizePolicy)
        self.lne_poruch.setMinimumSize(QtCore.QSize(160, 30))
        self.lne_poruch.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lne_poruch.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lne_poruch.setObjectName("lne_poruch")
        self.verticalLayout_2.addWidget(self.lne_poruch)
        self.dte_poruch = QtWidgets.QDateEdit(parent=self.tab_create_payment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dte_poruch.sizePolicy().hasHeightForWidth())
        self.dte_poruch.setSizePolicy(sizePolicy)
        self.dte_poruch.setMinimumSize(QtCore.QSize(160, 30))
        self.dte_poruch.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.dte_poruch.setSizeIncrement(QtCore.QSize(0, 0))
        self.dte_poruch.setStyleSheet("")
        self.dte_poruch.setWrapping(False)
        self.dte_poruch.setFrame(True)
        self.dte_poruch.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.dte_poruch.setReadOnly(False)
        self.dte_poruch.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.dte_poruch.setDateTime(QtCore.QDateTime(QtCore.QDate(2023, 3, 30), QtCore.QTime(0, 0, 0)))
        self.dte_poruch.setCurrentSection(QtWidgets.QDateTimeEdit.Section.YearSection)
        self.dte_poruch.setCalendarPopup(True)
        self.dte_poruch.setCurrentSectionIndex(2)
        self.dte_poruch.setTimeSpec(QtCore.Qt.TimeSpec.LocalTime)
        self.dte_poruch.setDate(QtCore.QDate(2023, 3, 30))
        self.dte_poruch.setObjectName("dte_poruch")
        self.verticalLayout_2.addWidget(self.dte_poruch)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem8)
        self.lbl_platezh = QtWidgets.QLabel(parent=self.tab_create_payment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_platezh.sizePolicy().hasHeightForWidth())
        self.lbl_platezh.setSizePolicy(sizePolicy)
        self.lbl_platezh.setMinimumSize(QtCore.QSize(160, 30))
        self.lbl_platezh.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lbl_platezh.setStyleSheet("")
        self.lbl_platezh.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_platezh.setObjectName("lbl_platezh")
        self.verticalLayout_2.addWidget(self.lbl_platezh)
        self.lne_platezh = QtWidgets.QLineEdit(parent=self.tab_create_payment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lne_platezh.sizePolicy().hasHeightForWidth())
        self.lne_platezh.setSizePolicy(sizePolicy)
        self.lne_platezh.setMinimumSize(QtCore.QSize(160, 30))
        self.lne_platezh.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lne_platezh.setSizeIncrement(QtCore.QSize(0, 0))
        self.lne_platezh.setText("")
        self.lne_platezh.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lne_platezh.setObjectName("lne_platezh")
        self.verticalLayout_2.addWidget(self.lne_platezh)
        self.dte_platezh = QtWidgets.QDateEdit(parent=self.tab_create_payment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dte_platezh.sizePolicy().hasHeightForWidth())
        self.dte_platezh.setSizePolicy(sizePolicy)
        self.dte_platezh.setMinimumSize(QtCore.QSize(160, 30))
        self.dte_platezh.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.dte_platezh.setBaseSize(QtCore.QSize(0, 0))
        self.dte_platezh.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.dte_platezh.setCalendarPopup(True)
        self.dte_platezh.setCurrentSectionIndex(2)
        self.dte_platezh.setObjectName("dte_platezh")
        self.verticalLayout_2.addWidget(self.dte_platezh)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 2, 1)
        spacerItem9 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem9, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_create_payment, "")
        self.gridLayout_4.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Converter"))
        self.label.setText(_translate("MainWindow", "Данную программу используете на свой страх и риск, никто не несет ни за что ответственности"))
        self.btn_translate.setText(_translate("MainWindow", "Перевести описание"))
        self.btn_select_file.setText(_translate("MainWindow", "Выбрать файл"))
        self.btn_group_kod.setText(_translate("MainWindow", "Сгруппировать коды"))
        self.btn_load_csv.setText(_translate("MainWindow", "Загрузить CSV"))
        self.btn_load_tardek.setText(_translate("MainWindow", "Сформировать CSV для Тардека"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Change CSV"))
        self.btn_calc_tax.setText(_translate("MainWindow", "Рассчитать платежи"))
        self.btn_calc_csv.setText(_translate("MainWindow", "Рассчитать платежи из CSV файла"))
        self.btn_calc_lv.setText(_translate("MainWindow", "Сформировать расчет платежей для LV таможни"))
        self.label_warning.setText(_translate("MainWindow", "Расчет производится через сайт https://litarweb.lrmuitine.lt/ исключительно для ознакомления"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Calculation of payments"))
        self.lbl_avto.setText(_translate("MainWindow", "  Номер авто"))
        self.lbl_vid.setText(_translate("MainWindow", "  Номер св-ва"))
        self.btn_create_pay.setText(_translate("MainWindow", "Сформировать платежку"))
        self.lbl_pereh.setText(_translate("MainWindow", "Переход"))
        self.rdi_kyb.setText(_translate("MainWindow", "Kybartai, R., LTKBK3"))
        self.rdi_sal.setText(_translate("MainWindow", "Šalčininkai, LTSLK3"))
        self.rdi_lav.setText(_translate("MainWindow", "Lavoriškės, LTLVK3"))
        self.rdi_med.setText(_translate("MainWindow", "Medininkai, LTMDK3"))
        self.lbl_chedp.setText(_translate("MainWindow", "  Номер CHEDP"))
        self.lbl_poruch.setText(_translate("MainWindow", "Платежное поручение"))
        self.lbl_platezh.setText(_translate("MainWindow", "Номер платежки "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_create_payment), _translate("MainWindow", "Create payment"))
