# Form implementation generated from reading ui file 'dlg_settings.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlg_settings(object):
    def setupUi(self, dlg_settings):
        dlg_settings.setObjectName("dlg_settings")
        dlg_settings.resize(1006, 430)
        dlg_settings.setStyleSheet("QDialog {\n"
"    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid gray;\n"
"    border-radius: 20px;\n"
"    \n"
"    \n"
"}\n"
"QPushButton {\n"
"    background-color: rgb(22, 25, 31);\n"
"    color: white;\n"
"    font-size: 10pt;\n"
"    font-weight: 700;\n"
"    font-family: RussoOne-Regular;\n"
"    border: 1px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #888;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: white;\n"
"    font-family: RussoOne-Regular;\n"
"    font-size: 9pt;\n"
"    font-weight: 600;\n"
"    background: rgb(76, 81, 93);\n"
"    min-width: 26ex;\n"
"    min-height: 4ex;\n"
"    border: 1px;\n"
"    border-radius: 10px;\n"
"    \n"
"}\n"
"\n"
"QLineEdit {\n"
"    color: white;\n"
"    font-family: RussoOne-Regular;\n"
"    font-size: 12pt;\n"
"    font-weight: 600;\n"
"    background: rgb(76, 81, 93);\n"
"    border:1px;\n"
"    border: 1px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QDialogButtonBox {\n"
"    background-color: rgb(22, 25, 31);\n"
"    color: white;\n"
"    font-size: 20pt;\n"
"    font-weight: 700;\n"
"    font-family: RussoOne-Regular;\n"
"    border: 1px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QDialogButtonBox:hover {\n"
"    background-color: #666;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(dlg_settings)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_csv_razbivka = QtWidgets.QLabel(parent=dlg_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_csv_razbivka.sizePolicy().hasHeightForWidth())
        self.lbl_csv_razbivka.setSizePolicy(sizePolicy)
        self.lbl_csv_razbivka.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_csv_razbivka.setObjectName("lbl_csv_razbivka")
        self.horizontalLayout_2.addWidget(self.lbl_csv_razbivka)
        self.lne_csv_razbivka = QtWidgets.QLineEdit(parent=dlg_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lne_csv_razbivka.sizePolicy().hasHeightForWidth())
        self.lne_csv_razbivka.setSizePolicy(sizePolicy)
        self.lne_csv_razbivka.setObjectName("lne_csv_razbivka")
        self.horizontalLayout_2.addWidget(self.lne_csv_razbivka)
        self.btn_csv_razbivka = QtWidgets.QPushButton(parent=dlg_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_csv_razbivka.sizePolicy().hasHeightForWidth())
        self.btn_csv_razbivka.setSizePolicy(sizePolicy)
        self.btn_csv_razbivka.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_csv_razbivka.setObjectName("btn_csv_razbivka")
        self.horizontalLayout_2.addWidget(self.btn_csv_razbivka)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbl_csv_for_tardek = QtWidgets.QLabel(parent=dlg_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_csv_for_tardek.sizePolicy().hasHeightForWidth())
        self.lbl_csv_for_tardek.setSizePolicy(sizePolicy)
        self.lbl_csv_for_tardek.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_csv_for_tardek.setObjectName("lbl_csv_for_tardek")
        self.horizontalLayout_3.addWidget(self.lbl_csv_for_tardek)
        self.lne_csv_for_tardek = QtWidgets.QLineEdit(parent=dlg_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lne_csv_for_tardek.sizePolicy().hasHeightForWidth())
        self.lne_csv_for_tardek.setSizePolicy(sizePolicy)
        self.lne_csv_for_tardek.setObjectName("lne_csv_for_tardek")
        self.horizontalLayout_3.addWidget(self.lne_csv_for_tardek)
        self.btn_csv_for_tardek = QtWidgets.QPushButton(parent=dlg_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_csv_for_tardek.sizePolicy().hasHeightForWidth())
        self.btn_csv_for_tardek.setSizePolicy(sizePolicy)
        self.btn_csv_for_tardek.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_csv_for_tardek.setObjectName("btn_csv_for_tardek")
        self.horizontalLayout_3.addWidget(self.btn_csv_for_tardek)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lbl_calc = QtWidgets.QLabel(parent=dlg_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_calc.sizePolicy().hasHeightForWidth())
        self.lbl_calc.setSizePolicy(sizePolicy)
        self.lbl_calc.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_calc.setObjectName("lbl_calc")
        self.horizontalLayout_4.addWidget(self.lbl_calc)
        self.lne_calc = QtWidgets.QLineEdit(parent=dlg_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lne_calc.sizePolicy().hasHeightForWidth())
        self.lne_calc.setSizePolicy(sizePolicy)
        self.lne_calc.setObjectName("lne_calc")
        self.horizontalLayout_4.addWidget(self.lne_calc)
        self.btn_calc = QtWidgets.QPushButton(parent=dlg_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_calc.sizePolicy().hasHeightForWidth())
        self.btn_calc.setSizePolicy(sizePolicy)
        self.btn_calc.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_calc.setObjectName("btn_calc")
        self.horizontalLayout_4.addWidget(self.btn_calc)
        self.gridLayout.addLayout(self.horizontalLayout_4, 3, 0, 1, 3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lbl_calc_for_lv = QtWidgets.QLabel(parent=dlg_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_calc_for_lv.sizePolicy().hasHeightForWidth())
        self.lbl_calc_for_lv.setSizePolicy(sizePolicy)
        self.lbl_calc_for_lv.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_calc_for_lv.setObjectName("lbl_calc_for_lv")
        self.horizontalLayout_5.addWidget(self.lbl_calc_for_lv)
        self.lne_calc_for_lv = QtWidgets.QLineEdit(parent=dlg_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lne_calc_for_lv.sizePolicy().hasHeightForWidth())
        self.lne_calc_for_lv.setSizePolicy(sizePolicy)
        self.lne_calc_for_lv.setObjectName("lne_calc_for_lv")
        self.horizontalLayout_5.addWidget(self.lne_calc_for_lv)
        self.btn_calc_for_lv = QtWidgets.QPushButton(parent=dlg_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_calc_for_lv.sizePolicy().hasHeightForWidth())
        self.btn_calc_for_lv.setSizePolicy(sizePolicy)
        self.btn_calc_for_lv.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_calc_for_lv.setObjectName("btn_calc_for_lv")
        self.horizontalLayout_5.addWidget(self.btn_calc_for_lv)
        self.gridLayout.addLayout(self.horizontalLayout_5, 4, 0, 1, 3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lbl_platezhka_fito = QtWidgets.QLabel(parent=dlg_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_platezhka_fito.sizePolicy().hasHeightForWidth())
        self.lbl_platezhka_fito.setSizePolicy(sizePolicy)
        self.lbl_platezhka_fito.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_platezhka_fito.setObjectName("lbl_platezhka_fito")
        self.horizontalLayout_6.addWidget(self.lbl_platezhka_fito)
        self.lne_platezhka_fito = QtWidgets.QLineEdit(parent=dlg_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lne_platezhka_fito.sizePolicy().hasHeightForWidth())
        self.lne_platezhka_fito.setSizePolicy(sizePolicy)
        self.lne_platezhka_fito.setObjectName("lne_platezhka_fito")
        self.horizontalLayout_6.addWidget(self.lne_platezhka_fito)
        self.btn_platezhka_fito = QtWidgets.QPushButton(parent=dlg_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_platezhka_fito.sizePolicy().hasHeightForWidth())
        self.btn_platezhka_fito.setSizePolicy(sizePolicy)
        self.btn_platezhka_fito.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_platezhka_fito.setObjectName("btn_platezhka_fito")
        self.horizontalLayout_6.addWidget(self.btn_platezhka_fito)
        self.gridLayout.addLayout(self.horizontalLayout_6, 6, 0, 1, 3)
        self.btn_save = QtWidgets.QPushButton(parent=dlg_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_save.sizePolicy().hasHeightForWidth())
        self.btn_save.setSizePolicy(sizePolicy)
        self.btn_save.setObjectName("btn_save")
        self.gridLayout.addWidget(self.btn_save, 7, 0, 1, 1)
        self.btn_reset = QtWidgets.QPushButton(parent=dlg_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_reset.sizePolicy().hasHeightForWidth())
        self.btn_reset.setSizePolicy(sizePolicy)
        self.btn_reset.setObjectName("btn_reset")
        self.gridLayout.addWidget(self.btn_reset, 7, 2, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lbl_platezhka = QtWidgets.QLabel(parent=dlg_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_platezhka.sizePolicy().hasHeightForWidth())
        self.lbl_platezhka.setSizePolicy(sizePolicy)
        self.lbl_platezhka.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_platezhka.setObjectName("lbl_platezhka")
        self.horizontalLayout_7.addWidget(self.lbl_platezhka)
        self.lne_platezhka = QtWidgets.QLineEdit(parent=dlg_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lne_platezhka.sizePolicy().hasHeightForWidth())
        self.lne_platezhka.setSizePolicy(sizePolicy)
        self.lne_platezhka.setObjectName("lne_platezhka")
        self.horizontalLayout_7.addWidget(self.lne_platezhka)
        self.btn_platezhka = QtWidgets.QPushButton(parent=dlg_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_platezhka.sizePolicy().hasHeightForWidth())
        self.btn_platezhka.setSizePolicy(sizePolicy)
        self.btn_platezhka.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_platezhka.setObjectName("btn_platezhka")
        self.horizontalLayout_7.addWidget(self.btn_platezhka)
        self.gridLayout.addLayout(self.horizontalLayout_7, 5, 0, 1, 3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setSpacing(7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_csv_file = QtWidgets.QLabel(parent=dlg_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_csv_file.sizePolicy().hasHeightForWidth())
        self.lbl_csv_file.setSizePolicy(sizePolicy)
        self.lbl_csv_file.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lbl_csv_file.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.lbl_csv_file.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_csv_file.setObjectName("lbl_csv_file")
        self.horizontalLayout.addWidget(self.lbl_csv_file)
        self.lne_csv_file = QtWidgets.QLineEdit(parent=dlg_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lne_csv_file.sizePolicy().hasHeightForWidth())
        self.lne_csv_file.setSizePolicy(sizePolicy)
        self.lne_csv_file.setObjectName("lne_csv_file")
        self.horizontalLayout.addWidget(self.lne_csv_file)
        self.btn_csv_file = QtWidgets.QPushButton(parent=dlg_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_csv_file.sizePolicy().hasHeightForWidth())
        self.btn_csv_file.setSizePolicy(sizePolicy)
        self.btn_csv_file.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_csv_file.setObjectName("btn_csv_file")
        self.horizontalLayout.addWidget(self.btn_csv_file)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 3)

        self.retranslateUi(dlg_settings)
        QtCore.QMetaObject.connectSlotsByName(dlg_settings)

    def retranslateUi(self, dlg_settings):
        _translate = QtCore.QCoreApplication.translate
        dlg_settings.setWindowTitle(_translate("dlg_settings", "Dialog"))
        self.lbl_csv_razbivka.setText(_translate("dlg_settings", "Путь для сохранения CSV разбивки"))
        self.btn_csv_razbivka.setText(_translate("dlg_settings", "..."))
        self.lbl_csv_for_tardek.setText(_translate("dlg_settings", "Путь для сохранения CSV файла для Tardek"))
        self.btn_csv_for_tardek.setText(_translate("dlg_settings", "..."))
        self.lbl_calc.setText(_translate("dlg_settings", "Путь для сохранения расчета платежей"))
        self.btn_calc.setText(_translate("dlg_settings", "..."))
        self.lbl_calc_for_lv.setText(_translate("dlg_settings", "Путь для сохранения расчета платежей для LV таможни"))
        self.btn_calc_for_lv.setText(_translate("dlg_settings", "..."))
        self.lbl_platezhka_fito.setText(_translate("dlg_settings", "Путь для сохранения платежки FITO"))
        self.btn_platezhka_fito.setText(_translate("dlg_settings", "..."))
        self.btn_save.setText(_translate("dlg_settings", "Save"))
        self.btn_reset.setText(_translate("dlg_settings", "Reset"))
        self.lbl_platezhka.setText(_translate("dlg_settings", "Путь для сохранения платежки VET"))
        self.btn_platezhka.setText(_translate("dlg_settings", "..."))
        self.lbl_csv_file.setText(_translate("dlg_settings", "Папка с CSV файлом"))
        self.btn_csv_file.setText(_translate("dlg_settings", "..."))
