# Form implementation generated from reading ui file 'new_doc.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_New_doc(object):
    def setupUi(self, New_doc):
        New_doc.setObjectName("New_doc")
        New_doc.resize(511, 222)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(New_doc.sizePolicy().hasHeightForWidth())
        New_doc.setSizePolicy(sizePolicy)
        New_doc.setStyleSheet("QDialog {\n"
"    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid gray;\n"
"    border-radius: 10px;\n"
"    \n"
"}\n"
"QPushButton {\n"
"    background-color: rgb(22, 25, 31);\n"
"    color: white;\n"
"    font-size: 10pt;\n"
"    font-weight: 700;\n"
"    font-family: RussoOne-Regular;\n"
"    border:1px;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #888;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: white;\n"
"    font-family: RussoOne-Regular;\n"
"    font-size: 10pt;\n"
"    font-weight: 600;\n"
"    background: rgb(76, 81, 93);\n"
"    min-width: 26ex;\n"
"    min-height: 4ex;\n"
"    border:1px;\n"
"    border-radius: 20px;\n"
"    \n"
"}\n"
"QLineEdit {\n"
"    color: white;\n"
"    font-family: RussoOne-Regular;\n"
"    font-size: 14pt;\n"
"    font-weight: 600;\n"
"    background: rgb(76, 81, 93);\n"
"    border:1px;\n"
"    border-radius: 10px;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(New_doc)
        self.gridLayout.setObjectName("gridLayout")
        self.current_cmb = QtWidgets.QComboBox(parent=New_doc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.current_cmb.sizePolicy().hasHeightForWidth())
        self.current_cmb.setSizePolicy(sizePolicy)
        self.current_cmb.setMinimumSize(QtCore.QSize(104, 16))
        self.current_cmb.setMaximumSize(QtCore.QSize(250, 40))
        self.current_cmb.setStyleSheet("QComboBox {\n"
"    color: white;\n"
"    font-family: RussoOne-Regular;\n"
"    font-size: 10pt;\n"
"    font-weight: 600;\n"
"    background: rgb(76, 81, 93);\n"
"    min-width: 26ex;\n"
"    min-height: 4ex;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"    border:1px;\n"
"    border-radius: 20px;\n"
"\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background: rgb(76, 81, 93);\n"
"}\n"
"\n"
"QComboBox:on { \n"
"    background: rgb(76, 81, 93);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"  color: white;\n"
"  background-color: rgb(76, 81, 93);\n"
"  \n"
"  selection-background-color: rgb(39, 44, 54);\n"
"}")
        self.current_cmb.setObjectName("current_cmb")
        self.gridLayout.addWidget(self.current_cmb, 2, 2, 1, 1)
        self.btn_ok = QtWidgets.QPushButton(parent=New_doc)
        self.btn_ok.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ok.sizePolicy().hasHeightForWidth())
        self.btn_ok.setSizePolicy(sizePolicy)
        self.btn_ok.setMaximumSize(QtCore.QSize(480, 60))
        self.btn_ok.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.btn_ok.setObjectName("btn_ok")
        self.gridLayout.addWidget(self.btn_ok, 3, 0, 1, 4)
        self.lbl_current = QtWidgets.QLabel(parent=New_doc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_current.sizePolicy().hasHeightForWidth())
        self.lbl_current.setSizePolicy(sizePolicy)
        self.lbl_current.setMinimumSize(QtCore.QSize(104, 16))
        self.lbl_current.setMaximumSize(QtCore.QSize(250, 40))
        self.lbl_current.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.lbl_current.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    font-family: RussoOne-Regular;\n"
"    font-size: 10pt;\n"
"    font-weight: 600;\n"
"    background: rgb(76, 81, 93);\n"
"    min-width: 26ex;\n"
"    min-height: 4ex;\n"
"    border:1px;\n"
"    border-radius: 20px;\n"
"    \n"
"}")
        self.lbl_current.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_current.setObjectName("lbl_current")
        self.gridLayout.addWidget(self.lbl_current, 1, 0, 1, 1)
        self.lne_nmb_doc = QtWidgets.QLineEdit(parent=New_doc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lne_nmb_doc.sizePolicy().hasHeightForWidth())
        self.lne_nmb_doc.setSizePolicy(sizePolicy)
        self.lne_nmb_doc.setMinimumSize(QtCore.QSize(104, 16))
        self.lne_nmb_doc.setMaximumSize(QtCore.QSize(250, 40))
        self.lne_nmb_doc.setObjectName("lne_nmb_doc")
        self.gridLayout.addWidget(self.lne_nmb_doc, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(parent=New_doc)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)

        self.retranslateUi(New_doc)
        QtCore.QMetaObject.connectSlotsByName(New_doc)

    def retranslateUi(self, New_doc):
        _translate = QtCore.QCoreApplication.translate
        New_doc.setWindowTitle(_translate("New_doc", "Добавить документ"))
        self.btn_ok.setText(_translate("New_doc", "OK"))
        self.lbl_current.setText(_translate("New_doc", "Номер документа"))
        self.label.setText(_translate("New_doc", "Тип документа"))
