# Form implementation generated from reading ui file 'one_cmr.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_one_cmr(object):
    def setupUi(self, one_cmr):
        one_cmr.setObjectName("one_cmr")
        one_cmr.resize(876, 284)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(one_cmr.sizePolicy().hasHeightForWidth())
        one_cmr.setSizePolicy(sizePolicy)
        one_cmr.setMouseTracking(True)
        one_cmr.setStyleSheet("QDialog {\n"
"    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid gray;\n"
"    border-radius: 20px;\n"
"    \n"
"    \n"
"}\n"
"QPushButton {\n"
"    background-color: rgb(22, 25, 31);\n"
"    color: white;\n"
"    font-size: 10pt;\n"
"    font-weight: 700;\n"
"    font-family: RussoOne-Regular;\n"
"    border: 1px;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #888;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: white;\n"
"    font-family: RussoOne-Regular;\n"
"    font-size: 10pt;\n"
"    font-weight: 600;\n"
"    background: rgb(76, 81, 93);\n"
"    min-width: 26ex;\n"
"    min-height: 4ex;\n"
"    border: 1px;\n"
"    border-radius: 20px;\n"
"    \n"
"}\n"
"\n"
"QComboBox {\n"
"    color: white;\n"
"    font-family: RussoOne-Regular;\n"
"    font-size: 10pt;\n"
"    font-weight: 600;\n"
"    background: rgb(76, 81, 93);\n"
"    min-width: 26ex;\n"
"    min-height: 4ex;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"    border: 1px;\n"
"    border-radius: 20px;\n"
"\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background: rgb(76, 81, 93);\n"
"}\n"
"\n"
"QComboBox:on { \n"
"    background: rgb(76, 81, 93);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"  color: white;\n"
"  background-color: rgb(76, 81, 93);\n"
"  \n"
"  selection-background-color: rgb(39, 44, 54);\n"
"}\n"
"\n"
"QLineEdit {\n"
"    color: white;\n"
"    font-family: RussoOne-Regular;\n"
"    font-size: 18pt;\n"
"    font-weight: 600;\n"
"    background: rgb(76, 81, 93);\n"
"    border:1px;\n"
"    border: 1px;\n"
"    border-radius: 20px;\n"
"     \n"
"\n"
"}\n"
"\n"
"QRadioButton {\n"
"    color: white;\n"
"    font-family: RussoOne-Regular;\n"
"    font-size: 10pt;\n"
"    font-weight: 600; \n"
"\n"
"}\n"
"\n"
"QCheckBox {\n"
"    \n"
"    color: white;\n"
"    font-size: 10pt;\n"
"    font-weight: 700;\n"
"    font-family: RussoOne-Regular;\n"
"    font-style: italic;\n"
"    \n"
"    \n"
"}\n"
"QCheckBox::indicator {\n"
"        width: 15px;\n"
"        height: 15px;\n"
"        border-radius: 9px; /* Делает форму круглой */\n"
"        border: 2px solid #555;\n"
"        background-color: white;\n"
"    }\n"
"    QCheckBox::indicator:checked {\n"
"        background-color: #0078d7;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(one_cmr)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_nbr_cmr = QtWidgets.QLabel(parent=one_cmr)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_nbr_cmr.sizePolicy().hasHeightForWidth())
        self.lbl_nbr_cmr.setSizePolicy(sizePolicy)
        self.lbl_nbr_cmr.setMinimumSize(QtCore.QSize(104, 16))
        self.lbl_nbr_cmr.setMaximumSize(QtCore.QSize(200, 60))
        font = QtGui.QFont()
        font.setFamily("RussoOne-Regular")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_nbr_cmr.setFont(font)
        self.lbl_nbr_cmr.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.lbl_nbr_cmr.setObjectName("lbl_nbr_cmr")
        self.gridLayout.addWidget(self.lbl_nbr_cmr, 0, 0, 1, 1)
        self.lne_numb_cmr = QtWidgets.QLineEdit(parent=one_cmr)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lne_numb_cmr.sizePolicy().hasHeightForWidth())
        self.lne_numb_cmr.setSizePolicy(sizePolicy)
        self.lne_numb_cmr.setMinimumSize(QtCore.QSize(80, 16))
        self.lne_numb_cmr.setMaximumSize(QtCore.QSize(300, 60))
        font = QtGui.QFont()
        font.setFamily("RussoOne-Regular")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lne_numb_cmr.setFont(font)
        self.lne_numb_cmr.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.lne_numb_cmr.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lne_numb_cmr.setObjectName("lne_numb_cmr")
        self.gridLayout.addWidget(self.lne_numb_cmr, 0, 1, 1, 1)
        self.lbl_nbr_inv = QtWidgets.QLabel(parent=one_cmr)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_nbr_inv.sizePolicy().hasHeightForWidth())
        self.lbl_nbr_inv.setSizePolicy(sizePolicy)
        self.lbl_nbr_inv.setMinimumSize(QtCore.QSize(104, 16))
        self.lbl_nbr_inv.setMaximumSize(QtCore.QSize(200, 60))
        font = QtGui.QFont()
        font.setFamily("RussoOne-Regular")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_nbr_inv.setFont(font)
        self.lbl_nbr_inv.setObjectName("lbl_nbr_inv")
        self.gridLayout.addWidget(self.lbl_nbr_inv, 1, 0, 1, 1)
        self.lne_numb_inv = QtWidgets.QLineEdit(parent=one_cmr)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lne_numb_inv.sizePolicy().hasHeightForWidth())
        self.lne_numb_inv.setSizePolicy(sizePolicy)
        self.lne_numb_inv.setMinimumSize(QtCore.QSize(104, 16))
        self.lne_numb_inv.setMaximumSize(QtCore.QSize(300, 60))
        self.lne_numb_inv.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.lne_numb_inv.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lne_numb_inv.setObjectName("lne_numb_inv")
        self.gridLayout.addWidget(self.lne_numb_inv, 1, 1, 1, 1)
        self.lbl_pakage = QtWidgets.QLabel(parent=one_cmr)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_pakage.sizePolicy().hasHeightForWidth())
        self.lbl_pakage.setSizePolicy(sizePolicy)
        self.lbl_pakage.setMinimumSize(QtCore.QSize(104, 16))
        self.lbl_pakage.setMaximumSize(QtCore.QSize(200, 60))
        self.lbl_pakage.setObjectName("lbl_pakage")
        self.gridLayout.addWidget(self.lbl_pakage, 2, 0, 1, 1)
        self.cmb_pakage = QtWidgets.QComboBox(parent=one_cmr)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmb_pakage.sizePolicy().hasHeightForWidth())
        self.cmb_pakage.setSizePolicy(sizePolicy)
        self.cmb_pakage.setMaximumSize(QtCore.QSize(300, 60))
        self.cmb_pakage.setObjectName("cmb_pakage")
        self.gridLayout.addWidget(self.cmb_pakage, 2, 1, 1, 1)
        self.btn_add_doc = QtWidgets.QPushButton(parent=one_cmr)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_add_doc.sizePolicy().hasHeightForWidth())
        self.btn_add_doc.setSizePolicy(sizePolicy)
        self.btn_add_doc.setMaximumSize(QtCore.QSize(200, 60))
        self.btn_add_doc.setObjectName("btn_add_doc")
        self.gridLayout.addWidget(self.btn_add_doc, 3, 0, 1, 1)
        self.btn_ok = QtWidgets.QPushButton(parent=one_cmr)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ok.sizePolicy().hasHeightForWidth())
        self.btn_ok.setSizePolicy(sizePolicy)
        self.btn_ok.setMaximumSize(QtCore.QSize(300, 60))
        self.btn_ok.setObjectName("btn_ok")
        self.gridLayout.addWidget(self.btn_ok, 3, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.gridLayout_2.setContentsMargins(-1, 0, 33, 2)
        self.gridLayout_2.setVerticalSpacing(12)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.check_alik_lt_3 = QtWidgets.QCheckBox(parent=one_cmr)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_alik_lt_3.sizePolicy().hasHeightForWidth())
        self.check_alik_lt_3.setSizePolicy(sizePolicy)
        self.check_alik_lt_3.setMinimumSize(QtCore.QSize(300, 30))
        self.check_alik_lt_3.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setFamily("RussoOne-Regular")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(87)
        self.check_alik_lt_3.setFont(font)
        self.check_alik_lt_3.setObjectName("check_alik_lt_3")
        self.gridLayout_2.addWidget(self.check_alik_lt_3, 0, 0, 1, 1)
        self.check_alik = QtWidgets.QCheckBox(parent=one_cmr)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_alik.sizePolicy().hasHeightForWidth())
        self.check_alik.setSizePolicy(sizePolicy)
        self.check_alik.setMinimumSize(QtCore.QSize(300, 30))
        self.check_alik.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setFamily("RussoOne-Regular")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(87)
        self.check_alik.setFont(font)
        self.check_alik.setObjectName("check_alik")
        self.gridLayout_2.addWidget(self.check_alik, 1, 0, 1, 1)
        self.check_piir = QtWidgets.QCheckBox(parent=one_cmr)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_piir.sizePolicy().hasHeightForWidth())
        self.check_piir.setSizePolicy(sizePolicy)
        self.check_piir.setMinimumSize(QtCore.QSize(300, 30))
        self.check_piir.setMaximumSize(QtCore.QSize(200, 30))
        self.check_piir.setObjectName("check_piir")
        self.gridLayout_2.addWidget(self.check_piir, 2, 0, 1, 1)
        self.check_netto = QtWidgets.QCheckBox(parent=one_cmr)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_netto.sizePolicy().hasHeightForWidth())
        self.check_netto.setSizePolicy(sizePolicy)
        self.check_netto.setMinimumSize(QtCore.QSize(300, 30))
        self.check_netto.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setFamily("RussoOne-Regular")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(87)
        self.check_netto.setFont(font)
        self.check_netto.setObjectName("check_netto")
        self.gridLayout_2.addWidget(self.check_netto, 3, 0, 1, 1)
        self.check_brutto = QtWidgets.QCheckBox(parent=one_cmr)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_brutto.sizePolicy().hasHeightForWidth())
        self.check_brutto.setSizePolicy(sizePolicy)
        self.check_brutto.setMinimumSize(QtCore.QSize(300, 30))
        self.check_brutto.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setFamily("RussoOne-Regular")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(87)
        self.check_brutto.setFont(font)
        self.check_brutto.setObjectName("check_brutto")
        self.gridLayout_2.addWidget(self.check_brutto, 4, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 2, 4, 1)

        self.retranslateUi(one_cmr)
        QtCore.QMetaObject.connectSlotsByName(one_cmr)

    def retranslateUi(self, one_cmr):
        _translate = QtCore.QCoreApplication.translate
        one_cmr.setWindowTitle(_translate("one_cmr", "Dialog"))
        self.lbl_nbr_cmr.setText(_translate("one_cmr", "    Номер CMR"))
        self.lbl_nbr_inv.setText(_translate("one_cmr", "    Номер инвойса"))
        self.lbl_pakage.setText(_translate("one_cmr", "    Тип упаковки"))
        self.btn_add_doc.setText(_translate("one_cmr", "Добавить документ"))
        self.btn_ok.setText(_translate("one_cmr", "OK"))
        self.check_alik_lt_3.setText(_translate("one_cmr", "AliExpress LT"))
        self.check_alik.setText(_translate("one_cmr", "AliExpress LV"))
        self.check_piir.setText(_translate("one_cmr", "PIIT"))
        self.check_netto.setText(_translate("one_cmr", "Вес нетто"))
        self.check_brutto.setText(_translate("one_cmr", "Вес брутто в каждый товар"))
