# Form implementation generated from reading ui file 'progress.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Progress_calc(object):
    def setupUi(self, Progress_calc):
        Progress_calc.setObjectName("Progress_calc")
        Progress_calc.resize(749, 328)
        Progress_calc.setStyleSheet("QWidget {\n"
"    \n"
"    background-color: rgb(22, 25, 31);\n"
"    border: 2px solid gray;\n"
"    border-radius: 10px;\n"
"    \n"
"    \n"
"}")
        self.gridLayout_2 = QtWidgets.QGridLayout(Progress_calc)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(parent=Progress_calc)
        self.frame.setStyleSheet("QFrame {\n"
"    \n"
"    background-color: rgb(35, 40, 49);\n"
"       \n"
"}\n"
"\n"
"\n"
"QLabel {\n"
"    color: white;\n"
"    font-family: RussoOne-Regular;\n"
"    font-size: 10pt;\n"
"    font-weight: 600;\n"
"    background: rgb(76, 81, 93);\n"
"    min-width: 26ex;\n"
"    min-height: 4ex;\n"
"    border: 2px solid gray;\n"
"    border-radius: 10px;\n"
"    \n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_process = QtWidgets.QLabel(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_process.sizePolicy().hasHeightForWidth())
        self.lbl_process.setSizePolicy(sizePolicy)
        self.lbl_process.setMinimumSize(QtCore.QSize(108, 20))
        self.lbl_process.setMaximumSize(QtCore.QSize(800, 50))
        self.lbl_process.setText("")
        self.lbl_process.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_process.setObjectName("lbl_process")
        self.gridLayout.addWidget(self.lbl_process, 2, 0, 1, 1)
        self.lbl_calc = QtWidgets.QLabel(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_calc.sizePolicy().hasHeightForWidth())
        self.lbl_calc.setSizePolicy(sizePolicy)
        self.lbl_calc.setMinimumSize(QtCore.QSize(108, 20))
        self.lbl_calc.setMaximumSize(QtCore.QSize(800, 50))
        self.lbl_calc.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_calc.setObjectName("lbl_calc")
        self.gridLayout.addWidget(self.lbl_calc, 0, 0, 1, 1)
        self.prgbar = QtWidgets.QProgressBar(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prgbar.sizePolicy().hasHeightForWidth())
        self.prgbar.setSizePolicy(sizePolicy)
        self.prgbar.setMaximumSize(QtCore.QSize(800, 50))
        self.prgbar.setStyleSheet("QProgressBar {\n"
"    color: white;\n"
"    font-family: RussoOne-Regular;\n"
"    font-size: 10pt;\n"
"    font-weight: 600;\n"
"    background-color: rgb(76, 81, 93);\n"
"    min-width: 26ex;\n"
"    min-height: 4ex;\n"
"    background-color: rgb(22, 25, 31);\n"
"    border: 2px solid gray;\n"
"    border-radius: 10px;\n"
"    \n"
"    \n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    \n"
"    color: white;\n"
"    font-family: RussoOne-Regular;\n"
"    font-size: 10pt;\n"
"    font-weight: 600;\n"
"    background-color: rgb(76, 81, 93);\n"
"    min-width: 26ex;\n"
"    min-height: 4ex;\n"
"    border: 2px solid gray;\n"
"    border-radius: 10px;\n"
"\n"
"}")
        self.prgbar.setProperty("value", 25)
        self.prgbar.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.prgbar.setTextVisible(True)
        self.prgbar.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.prgbar.setObjectName("prgbar")
        self.gridLayout.addWidget(self.prgbar, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Progress_calc)
        QtCore.QMetaObject.connectSlotsByName(Progress_calc)

    def retranslateUi(self, Progress_calc):
        _translate = QtCore.QCoreApplication.translate
        Progress_calc.setWindowTitle(_translate("Progress_calc", "Form"))
        self.lbl_calc.setText(_translate("Progress_calc", "Выполняется рассчет..."))
