# Form implementation generated from reading ui file 'table_rate.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_table_rate(object):
    def setupUi(self, table_rate):
        table_rate.setObjectName("table_rate")
        table_rate.resize(625, 354)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(table_rate.sizePolicy().hasHeightForWidth())
        table_rate.setSizePolicy(sizePolicy)
        table_rate.setStyleSheet("QDialog {\n"
"    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid gray;\n"
"    border-radius: 10px;\n"
"    \n"
"    \n"
"}\n"
"QPushButton {\n"
"    background-color: rgb(22, 25, 31);\n"
"    color: white;\n"
"    font-size: 10pt;\n"
"    font-weight: 700;\n"
"    font-family: RussoOne-Regular;\n"
"    border:1px;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #888;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: white;\n"
"    font-family: RussoOne-Regular;\n"
"    font-size: 12pt;\n"
"    font-weight: 600;\n"
"    background: rgb(76, 81, 93);\n"
"    min-width: 26ex;\n"
"    min-height: 4ex;\n"
"    border:1px;\n"
"    border-radius: 20px;\n"
"    \n"
"}\n"
"\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(table_rate)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_ok = QtWidgets.QPushButton(parent=table_rate)
        self.btn_ok.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ok.sizePolicy().hasHeightForWidth())
        self.btn_ok.setSizePolicy(sizePolicy)
        self.btn_ok.setObjectName("btn_ok")
        self.gridLayout.addWidget(self.btn_ok, 4, 0, 1, 2)
        self.total_lbl = QtWidgets.QLabel(parent=table_rate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.total_lbl.sizePolicy().hasHeightForWidth())
        self.total_lbl.setSizePolicy(sizePolicy)
        self.total_lbl.setMinimumSize(QtCore.QSize(130, 20))
        self.total_lbl.setMaximumSize(QtCore.QSize(500, 50))
        self.total_lbl.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.total_lbl.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.total_lbl.setObjectName("total_lbl")
        self.gridLayout.addWidget(self.total_lbl, 3, 1, 1, 1)
        self.tax_lbl = QtWidgets.QLabel(parent=table_rate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tax_lbl.sizePolicy().hasHeightForWidth())
        self.tax_lbl.setSizePolicy(sizePolicy)
        self.tax_lbl.setMinimumSize(QtCore.QSize(130, 20))
        self.tax_lbl.setMaximumSize(QtCore.QSize(200, 40))
        self.tax_lbl.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.tax_lbl.setObjectName("tax_lbl")
        self.gridLayout.addWidget(self.tax_lbl, 1, 0, 1, 1)
        self.tbl_wdg = QtWidgets.QTableWidget(parent=table_rate)
        self.tbl_wdg.setMinimumSize(QtCore.QSize(106, 18))
        self.tbl_wdg.setMaximumSize(QtCore.QSize(900, 120))
        self.tbl_wdg.setStyleSheet("QTableWidget {\n"
"    color: white;\n"
"    font-family: RussoOne-Regular;\n"
"    font-size: 10pt;\n"
"    font-weight: 600;\n"
"    background: rgb(76, 81, 93);\n"
"    min-width: 26ex;\n"
"    min-height: 4ex;\n"
"    \n"
"}\n"
"\n"
"\n"
"QHeaderView::section {\n"
"    background-color: rgb(22, 25, 31);\n"
"    color: white;\n"
"    font-size: 10pt;\n"
"    font-weight: 700;\n"
"    font-family: RussoOne-Regular;\n"
"  \n"
"}\n"
"\n"
"QTableWidget::item {\n"
"border: 1px dashed #000000; \n"
"}")
        self.tbl_wdg.setObjectName("tbl_wdg")
        self.tbl_wdg.setColumnCount(0)
        self.tbl_wdg.setRowCount(0)
        self.gridLayout.addWidget(self.tbl_wdg, 2, 0, 1, 2)
        self.comm_lbl = QtWidgets.QLabel(parent=table_rate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comm_lbl.sizePolicy().hasHeightForWidth())
        self.comm_lbl.setSizePolicy(sizePolicy)
        self.comm_lbl.setMinimumSize(QtCore.QSize(130, 20))
        self.comm_lbl.setMaximumSize(QtCore.QSize(350, 50))
        self.comm_lbl.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.comm_lbl.setObjectName("comm_lbl")
        self.gridLayout.addWidget(self.comm_lbl, 0, 0, 1, 2)

        self.retranslateUi(table_rate)
        QtCore.QMetaObject.connectSlotsByName(table_rate)

    def retranslateUi(self, table_rate):
        _translate = QtCore.QCoreApplication.translate
        table_rate.setWindowTitle(_translate("table_rate", "Taxes Sum"))
        self.btn_ok.setText(_translate("table_rate", "OK"))
        self.total_lbl.setText(_translate("table_rate", "Total Amount: 167  EUR"))
        self.tax_lbl.setText(_translate("table_rate", "Taxes Sum"))
        self.comm_lbl.setText(_translate("table_rate", "Commodity Code"))
